const seed=[
{name:"Amlaki",sanskrit:"Āmalakī",botanical:"Phyllanthus emblica",family:"Phyllanthaceae",common:"Indian gooseberry, Amla",rasa:"Five tastes except Lavana",guna:"Laghu, Ruksha",virya:"Shita",vipaka:"Madhura",karma:"Rasayana, Tridosha balancing",part:"Fruit",uses:"Traditional Ayurvedic use includes rasayana and digestive support.",features:"Small to medium tree; round pale green-yellow fruits with vertical grooves."},
{name:"Ashwagandha",sanskrit:"Aśvagandhā",botanical:"Withania somnifera",family:"Solanaceae",common:"Indian ginseng",rasa:"Tikta, Kashaya",guna:"Laghu, Snigdha",virya:"Ushna",vipaka:"Madhura",karma:"Balya, Rasayana",part:"Root",uses:"Traditionally used as a rasayana and for supporting strength and vitality.",features:"Low shrub with oval leaves and small greenish flowers; orange-red berries."},
{name:"Arjuna",sanskrit:"Arjuna",botanical:"Terminalia arjuna",family:"Combretaceae",common:"Arjun tree",rasa:"Kashaya",guna:"Laghu, Ruksha",virya:"Shita",vipaka:"Katu",karma:"Hridya, Kashaya",part:"Bark",uses:"Traditional Ayurvedic use includes hridya applications.",features:"Large tree with smooth pale bark and elongated leaves."},
{name:"Ashoka",sanskrit:"Aśoka",botanical:"Saraca asoca",family:"Fabaceae",common:"Ashoka tree",rasa:"Kashaya",guna:"Laghu",virya:"Shita",vipaka:"Katu",karma:"Traditional stri-roga related use",part:"Bark",uses:"Traditional Ayurvedic use includes stri-roga related formulations.",features:"Evergreen tree; dense foliage and clusters of orange-red flowers."},
{name:"Guduchi",sanskrit:"Guḍūcī",botanical:"Tinospora cordifolia",family:"Menispermaceae",common:"Giloy",rasa:"Tikta, Kashaya",guna:"Laghu, Snigdha",virya:"Ushna",vipaka:"Madhura",karma:"Rasayana",part:"Stem",uses:"Traditionally described as a rasayana and used in various Ayurvedic formulations.",features:"Large climbing vine with heart-shaped leaves and characteristic warty stem."},
{name:"Tulsi",sanskrit:"Tulasī",botanical:"Ocimum tenuiflorum",family:"Lamiaceae",common:"Holy basil",rasa:"Katu, Tikta",guna:"Laghu, Ruksha",virya:"Ushna",vipaka:"Katu",karma:"Krimighna, traditional respiratory use",part:"Leaf",uses:"Traditional use in respiratory and digestive formulations.",features:"Aromatic branching herb with opposite leaves and terminal flower spikes."},
{name:"Neem",sanskrit:"Nimba",botanical:"Azadirachta indica",family:"Meliaceae",common:"Neem",rasa:"Tikta, Kashaya",guna:"Laghu, Ruksha",virya:"Shita",vipaka:"Katu",karma:"Krimighna, traditional skin use",part:"Leaf/Bark",uses:"Traditional Ayurvedic use includes skin and cleansing formulations.",features:"Medium-large tree with pinnate leaves and small white fragrant flowers."}
];
let db=JSON.parse(localStorage.getItem("fmd_db")||"null")||seed;
let fav=new Set(JSON.parse(localStorage.getItem("fmd_fav")||"[]"));
function save(){localStorage.setItem("fmd_db",JSON.stringify(db));localStorage.setItem("fmd_fav",JSON.stringify([...fav]))}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function go(hash){location.hash=hash}
function card(d){return `<article class="card"><span class="tag">${esc(d.part)}</span><h3>${esc(d.name)}</h3><div class="latin">${esc(d.botanical)}</div><div class="meta"><span>Rasa: ${esc(d.rasa)}</span><span>Virya: ${esc(d.virya)}</span></div><button class="link" onclick='go("#dravya/${encodeURIComponent(d.name)}")'>View Dravya →</button></article>`}
function home(){return `<section class="hero"><div><span class="eyebrow">Modern Ayurvedic reference</span><h1>Find My<br>Dravya 🌿</h1><p>Explore Ayurvedic Dravyas with botanical names, traditional properties and plant identification features.</p><div class="actions"><button class="btn primary" onclick="go('#scan')">📷 Scan a Plant</button><button class="btn secondary" onclick="go('#library')">Explore Library</button></div></div><div class="heroart">🌱</div></section><section class="section"><span class="eyebrow">Featured</span><h2>Popular Dravyas</h2><div class="grid">${db.slice(0,3).map(card).join("")}</div></section>`}
function library(){return `<section class="section"><div class="head"><div><span class="eyebrow">Reference library</span><h2>Ayurvedic Dravyas</h2></div><input class="search" id="search" placeholder="Search Dravya..." oninput="filter(this.value)"></div><div id="results" class="grid">${db.map(card).join("")}</div></section>`}
function filter(q){q=q.toLowerCase();let a=db.filter(d=>Object.values(d).join(" ").toLowerCase().includes(q));document.getElementById("results").innerHTML=a.length?a.map(card).join(""):'<div class="empty card">No Dravya found.</div>'}
function profile(name){let d=db.find(x=>x.name===decodeURIComponent(name));if(!d)return `<section class="section empty">Dravya not found.</section>`;let saved=fav.has(d.name);return `<section class="section profile"><div class="profilehero"><span class="tag">${esc(d.family)}</span><h1>${esc(d.name)}</h1><div class="latin">${esc(d.sanskrit)} • ${esc(d.botanical)}</div><div class="actions"><button class="btn secondary" onclick='toggleFav(${JSON.stringify(d.name)})'>${saved?"♥ Saved":"♡ Save Favorite"}</button><button class="btn secondary" onclick="go('#library')">← Library</button></div></div><div class="facts">${fact("Common names",d.common)}${fact("Rasa",d.rasa)}${fact("Guna",d.guna)}${fact("Virya",d.virya)}${fact("Vipaka",d.vipaka)}${fact("Karma",d.karma)}${fact("Part used",d.part)}${fact("Identification features",d.features)}${fact("Traditional uses",d.uses)}</div></section>`}
function fact(a,b){return `<div class="fact"><b>${esc(a)}</b>${esc(b)}</div>`}
function toggleFav(n){fav.has(n)?fav.delete(n):fav.add(n);save();render();toast(fav.has(n)?"Saved to favorites":"Removed from favorites")}
function favorites(){let a=db.filter(d=>fav.has(d.name));return `<section class="section"><span class="eyebrow">Your collection</span><h2>Favorites</h2><div class="grid">${a.length?a.map(card).join(""):'<div class="empty card">No favorites yet.</div>'}</div></section>`}
function scan(){return `<section class="section scanner"><span class="eyebrow">Plant scanner</span><h2>Scan or upload a plant</h2><p class="muted">Take a photo with your phone camera or choose an image. The interface is ready for a validated plant-identification model.</p><div class="drop"><div class="dropicon">📷</div><h3>Choose a plant image</h3><input id="photo" type="file" accept="image/*" capture="environment" onchange="preview(event)" hidden><button class="btn primary" onclick="photo.click()">Open Camera / Gallery</button><img id="preview" class="preview"><div id="scanmsg"></div></div></section>`}
function preview(e){let f=e.target.files[0];if(!f)return;let u=URL.createObjectURL(f),p=document.getElementById("preview");p.src=u;p.style.display="block";document.getElementById("scanmsg").innerHTML='<div class="card" style="margin-top:18px"><b>Photo captured successfully.</b><p class="muted">Automatic identification is not claimed until a validated plant model is connected.</p><button class="btn secondary" onclick="go('#library')">Compare with Dravya Library</button></div>'}
function owner(){return `<section class="section"><span class="eyebrow">Owner area</span><h2>Aditya — Content Manager</h2><div class="adminnote">Your edits are stored in this browser using local storage. This is suitable for a free static website, but it is not a secure online admin panel.</div><div class="card" style="margin-top:18px"><form class="form" onsubmit="add(event)"><input id="n" required placeholder="Dravya name"><input id="s" placeholder="Sanskrit name"><input id="b" required placeholder="Botanical name"><input id="f" placeholder="Family"><input id="c" placeholder="Common names"><input id="r" placeholder="Rasa"><input id="g" placeholder="Guna"><input id="v" placeholder="Virya"><input id="vp" placeholder="Vipaka"><input id="k" placeholder="Karma"><input id="p" placeholder="Part used"><textarea id="u" placeholder="Traditional uses"></textarea><textarea id="i" placeholder="Identification features"></textarea><button class="btn primary">Add Dravya</button></form></div><h3 style="margin-top:28px">Your local Dravya database</h3>${db.map((d,i)=>`<div class="card listrow" style="margin:9px 0"><b>${esc(d.name)}</b><button class="btn secondary" onclick="del(${i})">Delete</button></div>`).join("")}</section>`}
function add(e){e.preventDefault();db.push({name:n.value,sanskrit:s.value,botanical:b.value,family:f.value,common:c.value,rasa:r.value,guna:g.value,virya:v.value,vipaka:vp.value,karma:k.value,part:p.value,uses:u.value,features:i.value});save();go("#owner");toast("Dravya added")}
function del(i){if(confirm("Delete this local Dravya?")){db.splice(i,1);save();render();toast("Deleted")}}
function render(){let h=location.hash||"#home",parts=h.slice(1).split("/"),p=parts[0];document.getElementById("app").innerHTML=p==="home"?home():p==="library"?library():p==="favorites"?favorites():p==="scan"?scan():p==="owner"?owner():p==="dravya"?profile(parts.slice(1).join("/")):home()}
window.addEventListener("hashchange",render);render();
function toast(t){let x=document.querySelector(".toast");if(!x){x=document.createElement("div");x.className="toast";document.body.appendChild(x)}x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",1700)}